name: Build unpatched PaperMC

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    
    - name: Setup JDK 17
      uses: actions/setup-java@v2.3.1
      with:
          java-version: 17
          distribution: 'temurin'

    - name: Check Version and Build
      env:
        GH_REPO: ${{ github.repository }}
      run: |
        npm install
        npm start
      
    - name: Load output file to env
      uses: antifree/json-to-variables@v1.0.1
      with:
        filename: output.json

    - name: Create Release
      if: env.json_Update == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.json_FileName }}
        body: ${{ env.json_Body }}
        name: ${{ env.json_Title }}
        tag: ${{ env.json_Version }}
        token: ${{ secrets.GITHUB_TOKEN }}
      
