name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: 'temurin'

    - name: Configure git credentials
      uses: OleksiyRudenko/gha-git-credentials@v2.1.1
      with:
        global: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Version and Build
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm start
      
    - name: Load output file to env
      uses: antifree/json-to-variables@v1.0.1
      with:
        filename: output.json

    - name: Create Release
      if: env.json_Update == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.json_FileName }}
        body: ${{ env.json_Body }}
        name: ${{ env.json_Title }}
        tag: ${{ env.json_Version }}
        prerelease: ${{ env.json_PreRelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
      
